name: Deploy to AWS Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y awscli

      - name: Get GitHub Runner IP
        id: get_ip
        run: echo "IP=$(curl -s https://api64.ipify.org)" >> $GITHUB_ENV

      - name: Allow SSH Access from Runner IP
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ env.IP }}/32 \
            --region ${{ secrets.AWS_REGION }}

      - name: Copy Files to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_SERVER_HOST }}
          username: ${{ secrets.AWS_SERVER_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "."
          target: "~/node-app"

      - name: Install Node.js and PM2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_SERVER_HOST }}
          username: ${{ secrets.AWS_SERVER_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install -y nodejs npm
            sudo npm install -g pm2

      - name: Run Deployment Script
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_SERVER_HOST }}
          username: ${{ secrets.AWS_SERVER_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/node-app
            npm install
            pm2 start index.js --name "node-app"

      - name: Revoke SSH Access for Runner IP
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ env.IP }}/32 \
            --region ${{ secrets.AWS_REGION }}
